name: Actions Docker

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [ deploy/backend ]

# 환경설정
env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USER }}/no1recipe
  VERSION: ${{ github.sha }}
  NAME: no1recipe

jobs:
  # 빌드 Job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # github repository에서 checkout
      - name: Checkout
        uses: actions/checkout@v2
      # docker build 수행
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # docker hub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      # docker hub 빌드, 푸시
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ../../docker/back.Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:0.0.1
    # 배포 Job
  deploy:
    needs: build  # build 후에 실행되도록 정의
    name: Deploy
    runs-on: [ self-hosted, label-go ] # AWS ./configure에서 사용할 label명
    steps:
      - name: Login to no1recipe
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
      - name: Docker run
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:0.0.1
          docker run -d -p 80:3666 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:0.0.1
          docker cp ~/forYourRecipe/backend/.env ${{ env.NAME }}:/app
